#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# enable 256 colour supports
if [ "$TERM" = "xterm" ]
then
    export TERM=xterm-256color
fi

# Use Sublime Text when installed, else vim
if (( $+commands[subl] )) ; then
    export EDITOR=subl
else
    export EDITOR=vim
fi

export BROWSER=google-chrome
export VISUAL=subl

# Prioritize executables from /usr/local/bin
export PATH=$PATH:/usr/local/bin

# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/code"

# android
export PATH=$PATH:/home/ijks/code/android/android-studio/bin
export PATH=$PATH:/home/ijks/code/android/android-sdk-linux/tools
export PATH=$PATH:/home/ijks/code/android/android-sdk-linux/platform-tools

# Haskell
export PATH=$PATH:/home/ijks/.cabal/bin

# Go
export PATH=$PATH:/usr/local/go/bin

# Rust
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
