#
#   environment variables
#   loosely organized by: srry jk it's not organized
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# enable 256 colour supports
if [ "$TERM" = "xterm" ]
then
    export TERM=xterm-256color
fi

export EDITOR=nvim
export VISUAL=nvim

export BROWSER=google-chrome-beta

# Prioritize executables from /usr/local/bin
export PATH=$PATH:/usr/local/bin

# Personal binaries, scripts etc
export PATH=$PATH:$HOME/bin

# virtualenvwrapper
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/code"

# android
export PATH=$PATH:$HOME/android-studio/bin
export PATH=$PATH:$HOME/android-sdk-linux/tools
export PATH=$PATH:$HOME/android-sdk-linux/platform-tools

# Haskell
export PATH=$PATH:$HOME/.cabal/bin

# Go
export PATH=$PATH:/usr/local/go/bin

# Rust
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

# Processing
export PATH=$PATH:/home/ijks/code/processing
