#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export BROWSER=google-chrome

# MOAR COLOURS
export TERM=xterm-256color

# Autocorrect is annoying...
unsetopt CORRECT

# assorted aliases
alias py=python3
alias st='subl -a'
alias stf='subl -a .'

# rbenv stuff
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"