#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Autocorrect is annoying...
unsetopt CORRECT

# assorted aliases
alias py=python3
alias st='subl -a'
alias stf='subl -a .'
alias startmc='~/mcserv/Direwolf20/ServerStart.sh'

# rbenv stuff
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"