#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Autocorrect is annoying...
unsetopt CORRECT

# git + hub = github
# https://github.com/github/hub
alias git=hub

# package managers
alias ag='sudo apt-get'
alias pm='sudo pacman'

# assorted aliases
alias py=python3
alias ipy=ipython
alias bpy=bpython
alias st='subl -a'
alias stf='subl -n .'
alias stn='subl -n'
alias wo='pew workon'
alias gst='git status'
