#! /usr/bin/env zsh

setopt EXTENDED_GLOB
for rcfile in runcoms/^README.md(.N); do
  ln -s "$(pwd)/$rcfile" "$(dirname $(pwd))/.${rcfile:t}"
  # Use the dirname of the working directory instead of a relative path
  # Otherwise, the link won't be placed properly if the current directory is a symlink
done
unsetopt EXTENDED_GLOB
